### ISSUE TITLE
"guest ok" not applied

### ISSUE THREAD

**Issue by ivanjx** [MekayelAnik/samba-server-alpine#3]
there is no `guest ok` written to the conf file in the scripts

**Comment by ivanjx** [comment]
never mind. to set the public share without password and random username just use these vars:
```yaml
            SERVER_MIN_PROTOCOL: "SMB3_11"
            MAP_TO_GUEST: "bad user"
            GUEST_ACCOUNT: "guest"
            NUMBER_OF_USERS: "2"
            USER_NAME_1: "youruser"
            USER_PASS_1: "yourpassword"
            USER_1_UID: "1000"
            USER_1_GID: "1000"
            USER_NAME_2: "guest"
            USER_PASS_2: "guest"
            USER_2_UID: "2000"
            USER_2_GID: "2000"
            NUMBER_OF_SHARES: "2"
            SHARE_NAME_1: "Private"
            SHARE_1_ENCRYPT: "required"
            SHARE_1_READ_ONLY: "no"
            SHARE_1_BROWSEABLE: "yes"
            SHARE_1_WRITE_LIST: "youruser"
            SHARE_1_VALID_USERS: "youruser"
            SHARE_1_CREATE_MASK: "0774"
            SHARE_1_DIRECTORY_MASK: "0774"
            SHARE_NAME_2: "Guest"
            SHARE_2_COMMENT: "Guest"
            SHARE_2_FORCE_USER: "guest"
            SHARE_2_PUBLIC: "yes"
            SHARE_2_BROWSEABLE: "yes"
            SHARE_2_WRITEABLE: "yes"
            SHARE_2_CREATE_MASK: "0777"
            SHARE_2_DIRECTORY_MASK: "0777"
```
